#!/usr/bin/env python3
"""Prepare an isolated, reproducible build with selected optional modules.

The source checkout and existing destination directories are never overwritten.
Usage: python scripts/prepare_modules.py --output /tmp/notebook-build --modules multi-model-research,local-workspace
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import shutil
import subprocess


def prepare(root: Path, output: Path, selected: list[str]):
    root, output = root.resolve(), output.resolve()
    if output == root or root in output.parents or output.exists():
        raise ValueError('Choose a new staging directory outside the source checkout.')
    manifests = {p.parent.name: json.loads(p.read_text()) for p in (root/'modules').glob('*/module.json')}
    ordered, visiting = [], set()
    def visit(mid):
        if mid in ordered:
            return
        if mid not in manifests or mid in visiting:
            raise ValueError('Unknown module or dependency cycle: '+mid)
        visiting.add(mid)
        for dep in manifests[mid]['dependencies']:
            visit(dep)
        visiting.remove(mid)
        ordered.append(mid)
    for mid in selected:
        visit(mid)
    # Validate every overlay before creating a staging directory. Upstream drift
    # must be reviewed, never silently overwritten by a local customization.
    targets = set()
    for mid in ordered:
        index = root/'modules'/mid/'overlay.json'
        for patch in json.loads(index.read_text()) if index.exists() else []:
            relative = Path(patch['target'])
            if relative.is_absolute() or '..' in relative.parts or str(relative) in targets:
                raise ValueError('Unsafe or conflicting overlay: '+str(relative))
            targets.add(str(relative))
            original = root/relative
            digest = hashlib.sha256(original.read_bytes()).hexdigest() if original.exists() else None
            if digest != patch['sha256_before']:
                raise ValueError('Upstream file changed; rebase the module overlay: '+str(relative))
    files = subprocess.check_output(['git','ls-files','-c','-o','--exclude-standard','-z'],cwd=root).decode().split('\0')
    output.mkdir(parents=True)
    for name in dict.fromkeys(files):
        if not name:
            continue
        source = root/name
        if source.is_symlink():
            raise ValueError('Source symlinks are not allowed in module builds: '+name)
        if source.is_file():
            dest = output/name
            dest.parent.mkdir(parents=True,exist_ok=True)
            shutil.copy2(source,dest)
    imports, entries = ["import dynamic from 'next/dynamic'"], []
    for number, mid in enumerate(ordered):
        module = root/'modules'/mid
        index = module/'overlay.json'
        for patch in json.loads(index.read_text()) if index.exists() else []:
            dest = output/patch['target']
            dest.parent.mkdir(parents=True,exist_ok=True)
            shutil.copy2(module/'overlay'/patch['target'],dest)
        spec = manifests[mid].get('frontend')
        if not spec:
            continue
        shutil.copytree(module/'frontend',output/'frontend/src/modules'/mid)
        imports.append(f"const Page{number} = dynamic(() => import( '@/modules/{mid}/{spec['entry'].removesuffix('.tsx')}'))")
        if (module/'frontend/locales.ts').exists():
            imports.append(f"import {{ moduleLocales as locales{number} }} from '@/modules/{mid}/locales'")
            entries.append(f"  '{mid}': {{ Page: Page{number}, locales: locales{number} }},")
        else:
            entries.append(f"  '{mid}': {{ Page: Page{number} }},")
        route = spec['route'].strip('/')
        if not route or '..' in Path(route).parts:
            raise ValueError('Invalid frontend route')
        alias = output/'frontend/src/app/(dashboard)'/route/'page.tsx'
        if alias.exists():
            raise ValueError('Module route conflicts with a core route: '+route)
        alias.parent.mkdir(parents=True,exist_ok=True)
        alias.write_text("import { ModulePage } from '@/components/modules/ModulePage'\nexport default function Page() { return <ModulePage id="+json.dumps(mid)+" /> }\n")
    generated = output/'frontend/src/lib/modules/generated.ts'
    generated.write_text("// Generated by scripts/prepare_modules.py; edit module sources instead.\nimport type { ModuleEntry } from './types'\n"+'\n'.join(imports)+"\nexport const moduleEntries: Record<string, ModuleEntry> = {\n"+'\n'.join(entries)+"\n}\n")
    (output/'modules/installed.json').write_text(json.dumps(ordered,indent=2)+'\n')
    (output/'modules/build.json').write_text(json.dumps({'schema_version':1,'modules':ordered,'overlay_targets':sorted(targets)},indent=2)+'\n')
    return ordered


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output',type=Path,required=True)
    parser.add_argument('--modules',default='')
    args=parser.parse_args()
    installed=prepare(Path(__file__).resolve().parents[1],args.output,[x.strip() for x in args.modules.split(',') if x.strip()])
    print('Prepared modules: '+(', '.join(installed) or '(core only)'))
    print('Build directory: '+str(args.output.resolve()))
